model:
    algo: PartialCompletionMask
    total_iter: 56000
    lr_steps: [32000, 48000]
    lr_mults: [0.1, 0.1]
    lr: 0.001
    weight_decay: 0.0001
    optim: SGD
    warmup_lr: []
    warmup_steps: []
    use_rgb: False
    backbone_arch: unet2
    backbone_param:
        in_channels: 2
        n_classes: 2
    inmask_weight: 5.
